apiVersion: v1
kind: Service
metadata:
  name: test-api-development
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    app: test-api
status:
  loadBalancer: {}
  